defmodule Arbor.Core.TestServiceImpl do
  @moduledoc """
  Implementation of the `Arbor.Contracts.Test.SimpleService` contract.

  This module was generated by `mix arbor.gen.impl`.
  TODO: Add a proper module description.
  """

  @behaviour Arbor.Contracts.Test.SimpleService

  @doc false
  @impl true
  def stop_service() do
    # TODO: Implement this callback.
    {:error, :not_implemented}
  end

  @doc false
  @impl true
  def start_service(_arg1) do
    # TODO: Implement this callback.
    {:error, :not_implemented}
  end

  @doc false
  @impl true
  def get_status() do
    # TODO: Implement this callback.
    {:error, :not_implemented}
  end
end
